version: '3.9'
services:
  app:
    build: ./
    volumes:
      - ./:/usr/src/app
     # - /usr/src/app/node_modules
     # - node_modules:/usr/src/app/node_modules
    env_file: .env
    command: sh -c "${CONTAINER_APP_CMD}"
    ports:
      - "3001:3000"

# volumes:
#   node_modules:

# networks:
#   default:
#     name: ms-name
#     external: true